name: driver_app_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^1.1.0              # ws plugin
  flutter_blue: ^0.6.3+1                    # bluetooth
  geolocator: ^5.3.0                      # location
  location: ^3.0.1    
  intl: ^0.16.1                           # localization
  android_intent: ^0.3.6                  # open android intent
  permission_handler: ^4.4.0+hotfix.2     # permission request
  shared_preferences: ^0.5.8              # shared pref
  signature:  ^3.2.0                      # signature
  fdottedline: ^1.0.1                     # dashed border widget
  syncfusion_flutter_gauges: ^18.2.55     # gauges
  syncfusion_flutter_charts: ^18.2.55     # stepline
  flutter_datetime_picker: ^1.4.0         # time spinnner
  http: ^0.12.2                           # http request
  package_info: ^0.4.3                    # platfor info; build version etc
  # flutter_masked_text: ^0.8.0              # Masked input controller
  json_annotation: ^3.1.0                 
  # flutter_echarts: ^1.3.5
  # rxbus: ^0.0.1                        rxbus
  # rxdart: ^0.24.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  build_runner: ^1.7.2
  syncfusion_flutter_pdfviewer: ^18.3.44-beta


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.0               # serializer json

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
      # Images
  assets:
    - assets/logo.png
    - assets/ic_home.png
    - assets/ic_account.png
    - assets/ic_settings.png
    - assets/ic_login.png
    - assets/ic_pass.png
    - assets/ic_phone.png
    - assets/ic_truck.png
    - assets/ic_truck.svg
    - assets/ic_search.png
    - assets/ic_menu.png
    - assets/ic_police.png
    - assets/fact_check.svg
    - assets/ic_location.png
    - assets/ic_notes.png
    - assets/ic_play.png
    - assets/ic_pause.png
    - assets/ic_email.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
